global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'techno-events-monitoring'

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres_exporter:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'techno_events_db'

  # Node Exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'monitoring_server'

  # Custom Exporter
  - job_name: 'custom_api'
    static_configs:
      - targets: ['custom_exporter:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'techno_events_api'